#!/usr/bin/env python3
"""build_project_wiki.py -- generated reference pages for a Rails project under docs/wiki/ (#887).

WHY GENERATED. A hand-written reference is a transcription, and transcriptions rot: the maintainer
repo's README named version 1.3.1 while 1.80.0 shipped. Every page here is a join over a STRUCTURED
source (the `derived-artifacts` skill: never regex-parse generated prose), every count on a page is
asserted against the source's own total, and every page names the commit its inputs reflect.

  page                  source
  Architecture.md       docs/architecture/graph.json   (from /rails-flow:graph -- the structured parse of the app)
  Routes.md             graph.json route nodes + its `notes` (which say what the static parser could not model)
  Data-Model.md         db/schema.rb + graph.json association edges
  Jobs-And-Queues.md    graph.json job nodes + config/queue.yml + config/recurring.yml
  Components.md         graph.json component / stimulus / turbo nodes
  Dependencies.md       Gemfile.lock + package.json
  _Sidebar.md           generated index; Home.md is HAND-WRITTEN -- scaffolded once if missing, never overwritten

  (no flag)   write the generated pages          --check   rebuild in memory, DRIFT if the committed pages differ
  --print P   render one page to stdout           --json    the model the pages are rendered from
  --selftest

Exit 0 written / clean · 1 DRIFT · 2 a source could not be read · 3 not applicable (no graph.json: run
/rails-flow:graph first; or --check with no docs/wiki yet: build first). Rendered bytes are a function
of the inputs and nothing else -- no timestamps, no environment; the commit comes from graph.json.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import tempfile
from pathlib import Path

WIKI = Path("docs/wiki")
GRAPH = Path("docs/architecture/graph.json")
GENERATED = ("Architecture.md", "Routes.md", "Data-Model.md", "Jobs-And-Queues.md", "Components.md", "Dependencies.md", "_Sidebar.md")
HAND_WRITTEN = ("Home.md",)
BANNER = ("<!-- GENERATED by rails-flow/build_project_wiki.py from {sources} at commit {commit} — do not hand-edit.\n"
          "     Rebuild: python3 ${{CLAUDE_PLUGIN_ROOT}}/scripts/build_project_wiki.py   Drift: --check -->\n\n")


# ----------------------------------------------------------------------------- sources (structured)

def load_graph(root: Path) -> dict | None:
    p = root / GRAPH
    if not p.is_file():
        return None
    return json.loads(p.read_text(encoding="utf-8"))


def parse_schema(text: str) -> dict:
    """db/schema.rb -> {version, tables: {name: {columns: [(name, type, opts)], indexes: [(cols, name, unique)]}}}.
    schema.rb is Rails' own generated, regular DSL -- a structured source, not prose."""
    version = (re.search(r"define\(version:\s*([\d_]+)\)", text) or [None, ""])[1]
    tables: dict[str, dict] = {}
    for m in re.finditer(r'^\s*create_table\s+"([^"]+)"(.*?)do \|t\|\n(.*?)^\s*end\s*$', text, re.S | re.M):
        name, opts, body = m.group(1), m.group(2), m.group(3)
        cols, idx = [], []
        for line in body.splitlines():
            c = re.match(r'\s*t\.(\w+)\s+"([^"]+)"(.*)', line)
            if c and c.group(1) != "index":
                cols.append((c.group(2), c.group(1), c.group(3).strip(" ,")))
            i = re.match(r'\s*t\.index\s+\[([^\]]*)\](.*)', line)
            if i:
                cols_in = [x.strip().strip('"') for x in i.group(1).split(",") if x.strip()]
                iname = (re.search(r'name:\s*"([^"]+)"', i.group(2)) or [None, ""])[1]
                idx.append((cols_in, iname, "unique: true" in i.group(2)))
        tables[name] = {"columns": cols, "indexes": idx, "id": (re.search(r"id:\s*(:\w+)", opts) or [None, "bigint"])[1]}
    fks = re.findall(r'^\s*add_foreign_key\s+"([^"]+)",\s*"([^"]+)"', text, re.M)
    return {"version": version, "tables": tables, "foreign_keys": fks,
            "declared_tables": len(re.findall(r"^\s*create_table\s", text, re.M))}


def parse_yaml_subset(text: str) -> dict:
    """The two-level `key:` / `  key: value` shape queue.yml and recurring.yml use. ERB is left as text."""
    out: dict = {}
    cur: str | None = None
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].rstrip() if not raw.lstrip().startswith("#") else ""
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip())
        k, _, v = line.strip().partition(":")
        if indent == 0:
            cur = k.strip(); out[cur] = {} if v.strip() in ("", "&default") else v.strip()
        elif indent == 2 and cur is not None and isinstance(out[cur], dict):
            out[cur][k.strip()] = {} if v.strip() == "" else v.strip()
            sub = k.strip()
        elif indent >= 4 and cur is not None and isinstance(out.get(cur), dict) and isinstance(out[cur].get(sub), dict):
            out[cur][sub][k.strip()] = v.strip()
    return out


def parse_gemfile_lock(text: str) -> list[tuple[str, str]]:
    """Top-level DEPENDENCIES resolved to the versions in `specs:` -- what is actually installed."""
    specs = dict(re.findall(r"^    ([A-Za-z0-9_.-]+) \(([^)]+)\)$", text, re.M))
    deps_block = text.split("\nDEPENDENCIES\n", 1)[1] if "\nDEPENDENCIES\n" in text else ""
    deps = re.findall(r"^  ([A-Za-z0-9_.-]+)", deps_block, re.M)
    return [(d, specs.get(d, "?")) for d in deps]


def parse_package_json(text: str) -> list[tuple[str, str]]:
    d = json.loads(text)
    out = []
    for section in ("dependencies", "devDependencies"):
        out += sorted((k, v) for k, v in (d.get(section) or {}).items())
    return out


# ----------------------------------------------------------------------------- the model

def build_model(root: Path) -> dict:
    g = load_graph(root)
    if g is None:
        raise FileNotFoundError(GRAPH)
    nodes = g.get("nodes", []); edges = g.get("edges", []); flows = g.get("flows", [])
    by_type: dict[str, list[dict]] = {}
    for n in nodes:
        by_type.setdefault(n.get("type", "?"), []).append(n)
    schema_p = root / "db" / "schema.rb"
    schema = parse_schema(schema_p.read_text(encoding="utf-8")) if schema_p.is_file() else None
    q = root / "config" / "queue.yml"; r = root / "config" / "recurring.yml"
    queue_text = q.read_text(encoding="utf-8") if q.is_file() else None
    recurring = parse_yaml_subset(r.read_text(encoding="utf-8")) if r.is_file() else None
    gl = root / "Gemfile.lock"; pj = root / "package.json"
    gems = parse_gemfile_lock(gl.read_text(encoding="utf-8")) if gl.is_file() else None
    npm = parse_package_json(pj.read_text(encoding="utf-8")) if pj.is_file() else None
    return {"commit": str(g.get("commit", "?"))[:7], "generator": g.get("generator", "?"), "notes": g.get("notes", []),
            "nodes": nodes, "edges": edges, "flows": flows, "by_type": by_type,
            "layers": {L: sum(1 for n in nodes if n.get("layer") == L) for L in ("web", "domain", "async", "ui")},
            "schema": schema, "queue_text": queue_text, "recurring": recurring, "gems": gems, "npm": npm}


# ----------------------------------------------------------------------------- pages

def _banner(m: dict, *sources: str) -> str:
    return BANNER.format(sources=" + ".join(sources), commit=m["commit"])


def _table(headers: list[str], rows: list[list[str]]) -> str:
    esc = lambda s: str(s).replace("|", "\\|")
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    out += ["| " + " | ".join(esc(c) for c in r) + " |" for r in rows]
    return "\n".join(out) + "\n"


def page_architecture(m: dict) -> str:
    nodes, edges, flows = m["nodes"], m["edges"], m["flows"]
    kinds: dict[str, int] = {}
    for e in edges:
        kinds[e.get("kind", "?")] = kinds.get(e.get("kind", "?"), 0) + 1
    out = [_banner(m, "docs/architecture/graph.json"), "# Architecture\n",
           f"**{len(nodes)} nodes · {len(edges)} edges · {len(flows)} flows** at commit `{m['commit']}`, from `{m['generator']}`. "
           "The interactive graph is [`docs/architecture/index.html`](../architecture/index.html); the prose is [`graph.md`](../architecture/graph.md).\n",
           "## Layers\n", _table(["layer", "nodes", "kinds"], [[L, str(c), ", ".join(sorted({n.get('type', '?') for n in nodes if n.get('layer') == L}))] for L, c in m["layers"].items()]),
           "## Node kinds\n", _table(["kind", "count"], [[k, str(len(v))] for k, v in sorted(m["by_type"].items())]),
           "## Edge kinds\n", _table(["kind", "count"], [[k, str(v)] for k, v in sorted(kinds.items())]),
           "## Flows\n", _table(["flow", "entry", "steps"], [[f.get("name", f.get("id", "?")), f.get("entry", "?"), str(len(f.get("steps", [])))] for f in flows]) if flows else "_no flows in the graph_\n"]
    if m["notes"]:
        out += ["## What the parser could not model\n"] + [f"- {n}\n" for n in m["notes"]]
    return "\n".join(out)


def page_routes(m: dict) -> str:
    routes = m["by_type"].get("route", [])
    rows = []
    for n in sorted(routes, key=lambda n: n.get("id", "")):
        verb, _, rest = n.get("id", "").partition(" ")
        target = next((e["to"] for e in m["edges"] if e.get("from") == n.get("id") and e.get("kind") in ("routes_to", "handles", "references")), "")
        rows.append([verb, rest, target])
    out = [_banner(m, "docs/architecture/graph.json (route nodes)"), "# Routes\n",
           f"**{len(routes)} routes** parsed statically from `config/routes.rb` by `/rails-flow:graph` — not `bin/rails routes`, so this page can be built in any clone. ",
           "Where the static parser could not model a line, it says so below rather than dropping it.\n",
           _table(["verb", "path", "handled by"], rows) if rows else "_no route nodes in the graph_\n"]
    unmodelled = [n for n in m["notes"] if "route" in n.lower()]
    if unmodelled:
        out += ["## Not on this page\n"] + [f"- {n}\n" for n in unmodelled]
    return "\n".join(out)


def page_data_model(m: dict) -> str:
    s = m["schema"]
    if s is None:
        return _banner(m, "db/schema.rb") + "# Data model\n\n_no `db/schema.rb` in this project_\n"
    assoc = [e for e in m["edges"] if e.get("kind") in ("belongs_to", "has_many", "has_one", "has_and_belongs_to_many")]
    out = [_banner(m, "db/schema.rb", "docs/architecture/graph.json (association edges)"), "# Data model\n",
           f"**{len(s['tables'])} tables** (schema version `{s['version']}`), **{len(s['foreign_keys'])} foreign keys**, **{len(assoc)} associations** declared in models.\n"]
    for name, t in sorted(s["tables"].items()):
        out.append(f"## `{name}`\n")
        out.append(_table(["column", "type", "options"], [[c, ty, o] for c, ty, o in t["columns"]]))
        if t["indexes"]:
            out.append("Indexes: " + "; ".join(f"`{'+'.join(cols)}`{' (unique)' if u else ''}" for cols, _, u in t["indexes"]) + "\n")
    if assoc:
        out += ["## Associations (from the models)\n", _table(["from", "kind", "to"], [[e["from"], e["kind"], e["to"]] for e in sorted(assoc, key=lambda e: (e['from'], e['to']))])]
    if s["foreign_keys"]:
        out += ["## Foreign keys\n", _table(["from", "to"], [[a, b] for a, b in s["foreign_keys"]])]
    return "\n".join(out)


def page_jobs(m: dict) -> str:
    jobs = m["by_type"].get("job", []); mailers = m["by_type"].get("mailer", [])
    def enqueuers(n): return ", ".join(sorted({e["from"] for e in m["edges"] if e.get("to") == n.get("id") and e.get("kind") == "enqueues"})) or "—"
    out = [_banner(m, "docs/architecture/graph.json (job + mailer nodes)", "config/queue.yml", "config/recurring.yml"), "# Jobs and queues\n",
           f"**{len(jobs)} job classes · {len(mailers)} mailers** (a mailer's `deliver_later` is an enqueue too).\n",
           "## Jobs\n", _table(["job", "file", "enqueued by"], [[n.get("id"), n.get("file", ""), enqueuers(n)] for n in sorted(jobs, key=lambda n: n.get('id', ''))]) if jobs else "_no job nodes in the graph_\n",
           "## Mailers\n", _table(["mailer", "file", "enqueued by"], [[n.get("id"), n.get("file", ""), enqueuers(n)] for n in sorted(mailers, key=lambda n: n.get('id', ''))]) if mailers else "_no mailer nodes in the graph_\n"]
    if m["queue_text"] is not None:
        # The file IS the structured source; a parse of its lists and ERB reads worse than the file. Comments stripped.
        body = "\n".join(l for l in m["queue_text"].splitlines() if l.strip() and not l.lstrip().startswith("#"))
        out.append("## Queue configuration (`config/queue.yml`, verbatim)\n\n```yaml\n" + body + "\n```\n")
    if m["recurring"] is not None:
        rows = []
        for env, entries in m["recurring"].items():
            if isinstance(entries, dict):
                for name, spec in entries.items():
                    if isinstance(spec, dict):
                        rows.append([env, name, spec.get("class") or spec.get("command", "?"), spec.get("queue", "default"), spec.get("schedule", "?")])
        out += ["## Recurring (`config/recurring.yml`)\n", _table(["env", "task", "runs", "queue", "schedule"], rows) if rows else "_no recurring tasks declared_\n"]
    return "\n".join(out)


def page_components(m: dict) -> str:
    comps = m["by_type"].get("component", []); stim = m["by_type"].get("stimulus", []); turbo = m["by_type"].get("turbo", [])
    def renders(n): return ", ".join(sorted({e["from"] for e in m["edges"] if e.get("to") == n.get("id") and e.get("kind") == "renders"})) or "—"
    out = [_banner(m, "docs/architecture/graph.json (component / stimulus / turbo nodes)"), "# Components\n",
           f"**{len(comps)} view components · {len(stim)} Stimulus controllers · {len(turbo)} Turbo nodes.**\n",
           "## View components\n", _table(["component", "file", "rendered by"], [[n.get("id"), n.get("file", ""), renders(n)] for n in sorted(comps, key=lambda n: n.get('id', ''))]) if comps else "_none_\n",
           "## Stimulus controllers\n", _table(["controller", "file"], [[n.get("id"), n.get("file", "")] for n in sorted(stim, key=lambda n: n.get('id', ''))]) if stim else "_none_\n"]
    return "\n".join(out)


def page_dependencies(m: dict) -> str:
    out = [_banner(m, "Gemfile.lock", "package.json"), "# Dependencies\n"]
    if m["gems"] is not None:
        out += [f"## Gems — {len(m['gems'])} direct dependencies, resolved versions from `Gemfile.lock`\n", _table(["gem", "version"], [[g, v] for g, v in sorted(m["gems"])])]
    else:
        out.append("_no `Gemfile.lock`_\n")
    if m["npm"] is not None:
        out += [f"## npm — {len(m['npm'])} declared in `package.json`\n", _table(["package", "range"], [[p, v] for p, v in m["npm"]])]
    return "\n".join(out)


def page_sidebar(m: dict) -> str:
    return _banner(m, "the generated set") + "**Reference**\n\n" + "\n".join(f"- [{p[:-3].replace('-', ' ')}]({p[:-3]})" for p in GENERATED if not p.startswith("_")) + "\n\n**Guide**\n\n- [Home](Home)\n"


HOME_SEED = ("# {name}\n\nHand-written. This page is yours: what the system is for, who uses it, where to start reading. "
             "The reference pages in the sidebar are generated from the codebase and rebuilt at ship — do not edit them; "
             "edit the code or regenerate.\n")

PAGES = {"Architecture.md": page_architecture, "Routes.md": page_routes, "Data-Model.md": page_data_model,
         "Jobs-And-Queues.md": page_jobs, "Components.md": page_components, "Dependencies.md": page_dependencies, "_Sidebar.md": page_sidebar}


def render_all(m: dict) -> dict[str, str]:
    return {name: fn(m) for name, fn in PAGES.items()}


def assert_totals(m: dict, pages: dict[str, str]) -> list[str]:
    """Every count a page states must equal its source's own total (derived-artifacts rule 2)."""
    problems = []
    s = m["schema"]
    if s is not None and s["declared_tables"] != len(s["tables"]):
        problems.append(f"Data-Model: schema.rb declares {s['declared_tables']} create_table but {len(s['tables'])} parsed -- the parser missed a shape")
    if f"**{len(m['nodes'])} nodes" not in pages["Architecture.md"]:
        problems.append("Architecture: the node count on the page is not the graph's")
    if f"**{len(m['by_type'].get('route', []))} routes**" not in pages["Routes.md"]:
        problems.append("Routes: the route count on the page is not the graph's")
    return problems


# ----------------------------------------------------------------------------- CLI

def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="rebuild in memory; exit 1 on drift, write nothing")
    ap.add_argument("--print", metavar="PAGE", help="render one generated page to stdout, write nothing")
    ap.add_argument("--json", action="store_true", help="print the model the pages are rendered from")
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--root", default=".")
    a = ap.parse_args(argv)
    if a.selftest:
        return selftest()
    root = Path(a.root)
    if not (root / GRAPH).is_file():
        print(f"n/a: no {GRAPH.as_posix()} — run /rails-flow:graph first; the wiki is a join over that graph")
        return 3
    try:
        m = build_model(root)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"cannot read a source: {exc}", file=sys.stderr)
        return 2
    if a.json:
        print(json.dumps({k: v for k, v in m.items() if k not in ("nodes", "edges", "flows")}, indent=2, default=str))
        return 0
    pages = render_all(m)
    problems = assert_totals(m, pages)
    for p in problems:
        print(f"PROBLEM {p}", file=sys.stderr)
    if problems:
        return 2
    if a.print:
        if a.print not in pages:
            print(f"no such generated page: {a.print} (one of {', '.join(PAGES)})", file=sys.stderr)
            return 2
        sys.stdout.write(pages[a.print])
        return 0
    wiki = root / WIKI
    if a.check:
        if not wiki.is_dir():
            print(f"n/a: no {WIKI.as_posix()} yet — build it first (run without --check)")
            return 3
        drift = [n for n, text in pages.items() if not (wiki / n).is_file() or (wiki / n).read_text(encoding="utf-8") != text]
        for n in drift:
            print(f"DRIFT: {WIKI.as_posix()}/{n} is not a clean build of its sources — rebuild and commit it with the change that moved them")
        print("clean: every generated page matches its sources" if not drift else f"{len(drift)} page(s) drifted")
        return 1 if drift else 0
    wiki.mkdir(parents=True, exist_ok=True)
    written = []
    for n, text in pages.items():
        if not (wiki / n).is_file() or (wiki / n).read_text(encoding="utf-8") != text:
            (wiki / n).write_text(text, encoding="utf-8"); written.append(n)
    for n in HAND_WRITTEN:
        if not (wiki / n).is_file():
            (wiki / n).write_text(HOME_SEED.format(name=root.resolve().name), encoding="utf-8"); written.append(f"{n} (seeded once; yours from here)")
    print(f"wrote {len(written)} page(s): {', '.join(written) if written else 'nothing changed'} — commit {WIKI.as_posix()}/ with the change")
    return 0


# ----------------------------------------------------------------------------- selftest

def selftest() -> int:
    n, failures = 0, []

    def check(label: str, ok: bool, detail: str = "") -> None:
        nonlocal n
        n += 1
        if not ok:
            failures.append(f"{label}{(' — ' + detail) if detail else ''}")

    GRAPH_FIXTURE = {"commit": "abc1234def", "generator": "rails-flow/architecture_graph.py", "notes": ["2 route line(s) in config/routes.rb used DSL this static parser does not model"],
        "nodes": [{"id": "GET /invoices", "type": "route", "layer": "web", "file": "config/routes.rb"},
                  {"id": "InvoicesController", "type": "controller", "layer": "web", "file": "app/controllers/invoices_controller.rb"},
                  {"id": "Invoice", "type": "model", "layer": "domain", "file": "app/models/invoice.rb"},
                  {"id": "Customer", "type": "model", "layer": "domain", "file": "app/models/customer.rb"},
                  {"id": "SendInvoiceJob", "type": "job", "layer": "async", "file": "app/jobs/send_invoice_job.rb"},
                  {"id": "InvoiceMailer", "type": "mailer", "layer": "async", "file": "app/mailers/invoice_mailer.rb"},
                  {"id": "Ui::CardComponent", "type": "component", "layer": "ui", "file": "app/components/ui/card_component.rb"},
                  {"id": "clipboard", "type": "stimulus", "layer": "ui", "file": "app/javascript/controllers/clipboard_controller.js"}],
        "edges": [{"from": "GET /invoices", "to": "InvoicesController", "kind": "references"}, {"from": "Invoice", "to": "Customer", "kind": "belongs_to"},
                  {"from": "InvoicesController", "to": "SendInvoiceJob", "kind": "enqueues"}, {"from": "InvoicesController", "to": "Ui::CardComponent", "kind": "renders"},
                  {"from": "SendInvoiceJob", "to": "InvoiceMailer", "kind": "enqueues"}],
        "flows": [{"id": "GET /invoices -> InvoicesController#index", "name": "List invoices", "entry": "InvoicesController", "steps": [{"node": "InvoicesController#index", "does": "handle"}]}]}
    SCHEMA = ('ActiveRecord::Schema[8.1].define(version: 2026_08_30_011027) do\n  enable_extension "pg_catalog.plpgsql"\n'
              '  create_table "customers", id: :uuid, force: :cascade do |t|\n    t.string "name", null: false\n    t.datetime "created_at", null: false\n  end\n'
              '  create_table "invoices", force: :cascade do |t|\n    t.uuid "customer_id", null: false\n    t.decimal "total", precision: 12, scale: 2\n'
              '    t.index ["customer_id"], name: "index_invoices_on_customer_id"\n    t.index ["customer_id", "total"], name: "idx_ct", unique: true\n  end\n'
              '  add_foreign_key "invoices", "customers"\nend\n')
    QUEUE = 'default: &default\n  dispatchers:\n    - polling_interval: 1\n  workers:\n    - queues: "*"\n      threads: 3\n\ndevelopment:\n  <<: *default\n'
    RECURRING = '# examples:\n#   x:\n#     class: Y\n\nproduction:\n  clear_finished:\n    command: "SolidQueue::Job.clear_finished_in_batches"\n    schedule: every hour\n  nightly_invoices:\n    class: SendInvoiceJob\n    queue: background\n    schedule: at 2am every day\n'
    LOCK = 'GEM\n  remote: https://rubygems.org/\n  specs:\n    rails (8.1.3.1)\n    puma (7.0.3)\n    nokogiri (1.18.9)\n\nPLATFORMS\n  ruby\n\nDEPENDENCIES\n  puma (>= 5.0)\n  rails (~> 8.1)\n\nBUNDLED WITH\n   2.6.9\n'
    PKG = '{"name": "x", "dependencies": {"@hotwired/turbo-rails": "^8.0.0"}, "devDependencies": {"esbuild": "0.24.0"}}\n'

    def make(root: Path) -> None:
        for rel, text in {"docs/architecture/graph.json": json.dumps(GRAPH_FIXTURE), "db/schema.rb": SCHEMA, "config/queue.yml": QUEUE,
                          "config/recurring.yml": RECURRING, "Gemfile.lock": LOCK, "package.json": PKG}.items():
            (root / rel).parent.mkdir(parents=True, exist_ok=True); (root / rel).write_text(text, encoding="utf-8")

    s = parse_schema(SCHEMA)
    check("schema.rb: tables, columns, options, indexes, foreign keys and the version are parsed",
          set(s["tables"]) == {"customers", "invoices"} and s["version"] == "2026_08_30_011027"
          and len(s["tables"]["invoices"]["columns"]) == 2 and s["tables"]["invoices"]["columns"][1] == ("total", "decimal", "precision: 12, scale: 2")
          and len(s["tables"]["invoices"]["indexes"]) == 2 and s["tables"]["invoices"]["indexes"][1] == (["customer_id", "total"], "idx_ct", True)
          and s["foreign_keys"] == [("invoices", "customers")] and s["tables"]["customers"]["id"] == ":uuid", str(s)[:300])
    check("schema.rb: the parsed table count is asserted against the declared count", s["declared_tables"] == 2 == len(s["tables"]))
    r = parse_yaml_subset(RECURRING)
    check("recurring.yml: commented examples are ignored; entries carry class/command, queue, schedule",
          set(r) == {"production"} and r["production"]["nightly_invoices"] == {"class": "SendInvoiceJob", "queue": "background", "schedule": "at 2am every day"}
          and r["production"]["clear_finished"]["command"].startswith('"SolidQueue'), str(r))
    check("Gemfile.lock: direct dependencies resolved to installed versions", parse_gemfile_lock(LOCK) == [("puma", "7.0.3"), ("rails", "8.1.3.1")])
    check("package.json: dependencies and devDependencies", parse_package_json(PKG) == [("@hotwired/turbo-rails", "^8.0.0"), ("esbuild", "0.24.0")])

    with tempfile.TemporaryDirectory() as td:
        root = Path(td) / "app"; root.mkdir()
        check("no graph.json is n/a (exit 3), not a pass", main(["--root", str(root)]) == 3)
        make(root)
        m = build_model(root)
        pages = render_all(m)
        check("every generated page carries the banner with the graph's commit and its sources",
              all(p.startswith("<!-- GENERATED by rails-flow/build_project_wiki.py from") and "commit abc1234" in p for p in pages.values()))
        check("Architecture: node/edge/flow counts, layers, kinds and the parser's notes",
              "**8 nodes · 5 edges · 1 flows**" in pages["Architecture.md"] and "| web | 2 |" in pages["Architecture.md"]
              and "List invoices" in pages["Architecture.md"] and "static parser does not model" in pages["Architecture.md"], pages["Architecture.md"][:400])
        check("Routes: the route row names verb, path and the controller it reaches; unmodelled lines are on the page",
              "| GET | /invoices | InvoicesController |\n" in pages["Routes.md"] and "**1 routes**" in pages["Routes.md"] and "Not on this page" in pages["Routes.md"], pages["Routes.md"])
        check("Data model: tables with columns and indexes, associations from the models, foreign keys",
              "## `invoices`" in pages["Data-Model.md"] and "| total | decimal | precision: 12, scale: 2 |" in pages["Data-Model.md"]
              and "`customer_id+total` (unique)" in pages["Data-Model.md"] and "| Invoice | belongs_to | Customer |" in pages["Data-Model.md"]
              and "**2 tables**" in pages["Data-Model.md"], pages["Data-Model.md"][:500])
        check("Jobs: the job, who enqueues it, the mailer and its enqueuer, the queue config and the recurring schedule",
              "| SendInvoiceJob | app/jobs/send_invoice_job.rb | InvoicesController |" in pages["Jobs-And-Queues.md"]
              and "| InvoiceMailer | app/mailers/invoice_mailer.rb | SendInvoiceJob |" in pages["Jobs-And-Queues.md"]
              and "| production | nightly_invoices | SendInvoiceJob | background | at 2am every day |" in pages["Jobs-And-Queues.md"]
              and "```yaml" in pages["Jobs-And-Queues.md"] and "threads: 3" in pages["Jobs-And-Queues.md"], pages["Jobs-And-Queues.md"])
        check("Components: rendered-by is derived from renders edges",
              "| Ui::CardComponent | app/components/ui/card_component.rb | InvoicesController |" in pages["Components.md"] and "| clipboard |" in pages["Components.md"])
        check("Dependencies: gems with resolved versions and npm ranges",
              "| rails | 8.1.3.1 |" in pages["Dependencies.md"] and "| esbuild | 0.24.0 |" in pages["Dependencies.md"] and "2 direct dependencies" in pages["Dependencies.md"])
        check("the counts on the pages equal their sources' totals", assert_totals(m, pages) == [])
        check("rendering is deterministic: the same inputs give the same bytes", render_all(build_model(root)) == pages)
        check("--check with no wiki yet is n/a (exit 3): build first", main(["--check", "--root", str(root)]) == 3)
        check("a build writes the generated set and seeds Home.md once", main(["--root", str(root)]) == 0 and (root / WIKI / "Home.md").is_file()
              and all((root / WIKI / p).is_file() for p in GENERATED))
        (root / WIKI / "Home.md").write_text("# mine\n", encoding="utf-8")
        check("a clean tree passes --check (exit 0)", main(["--check", "--root", str(root)]) == 0)
        main(["--root", str(root)])
        check("a rebuild never overwrites the hand-written Home.md", (root / WIKI / "Home.md").read_text(encoding="utf-8") == "# mine\n")
        g = json.loads((root / GRAPH).read_text(encoding="utf-8")); g["nodes"].append({"id": "POST /invoices", "type": "route", "layer": "web", "file": "config/routes.rb"})
        (root / GRAPH).write_text(json.dumps(g), encoding="utf-8")
        check("a source that moved makes --check report DRIFT (exit 1)", main(["--check", "--root", str(root)]) == 1)
        (root / "db" / "schema.rb").write_text(SCHEMA + '\n  create_table "weird" do |t|\n', encoding="utf-8")   # an unterminated table the parser cannot see
        try:
            m2 = build_model(root); probs = assert_totals(m2, render_all(m2))
        except Exception as exc:  # noqa: BLE001
            probs = [f"crash {exc}"]
        check("a table the parser missed is a PROBLEM (declared 3, parsed 2), not a quietly shorter page", any("declares 3" in p and "2 parsed" in p for p in probs), str(probs))
        import contextlib, io
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            rc_bad = main(["--print", "Routes.md", "--root", str(root)])
        check("a source PROBLEM blocks --print: exit 2 and no page rendered", rc_bad == 2 and "# Routes" not in buf.getvalue())
        (root / "db" / "schema.rb").write_text(SCHEMA, encoding="utf-8")
        before = {q.name: q.read_bytes() for q in (root / WIKI).iterdir()}
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            rc = main(["--print", "Routes.md", "--root", str(root)])
        check("--print renders one page to stdout and writes nothing", rc == 0 and buf.getvalue().startswith("<!-- GENERATED") and "# Routes" in buf.getvalue()
              and {q.name: q.read_bytes() for q in (root / WIKI).iterdir()} == before)

    for f in failures:
        print(f"FAIL {f}")
    print(f"build_project_wiki selftest: {n} checks, {len(failures)} failure(s)")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
