#!/usr/bin/env python3
"""Generate the wiki's reference pages from the repository, so they cannot go stale silently.

WHY GENERATED RATHER THAN WRITTEN. The README this replaces was 913 lines naming version 1.3.1 while
the marketplace shipped 1.80.0, listing 5 of 42 commands, and missing two skills entirely. Nothing
caught it because nothing checked it -- a hand-written reference is a transcription, and this repo's
own `derived-artifacts` skill says transcriptions rot. Rename a command now and `--check` fails
instead of the wiki quietly lying.

WHY IN-REPO RATHER THAN A GITHUB WIKI. A GitHub wiki is a separate git repository: no pull request,
no review, and no gate. Publishing there is one `git push` from these files whenever it is wanted,
but the source of truth stays where the gates can reach it.

WHAT IS NOT GENERATED. Only the reference pages -- the ones that are a join over the manifest, the
plugins and the skills. Every page that needs judgement (what the system is FOR, how the loops fit
together, why the QA pass is independent) is hand-written and left alone. A generator that tried to
author those would produce exactly the tone nobody reads.

Exit codes:  0 written / clean · 1 DRIFT (`--check`) · 2 the repository could not be read

Stdlib only, no network.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WIKI = ROOT / "docs" / "wiki"
MANIFEST = ROOT / ".claude-plugin" / "marketplace.json"

# Which pages this script owns. Anything else under docs/wiki/ is hand-written and never touched --
# stated here rather than inferred, so a new narrative page cannot be clobbered by a rebuild.
GENERATED = ("Command-Reference.md", "Skills-Reference.md", "Plugin-Reference.md")

BANNER = ("<!-- GENERATED by scripts/build_wiki.py — do not hand-edit.\n"
          "     Rebuild:  python3 scripts/build_wiki.py\n"
          "     Drift:    python3 scripts/build_wiki.py --check  (runs in the gate sweep) -->\n")

# What each command group is FOR. A bare list of names is an index, not a reference, and the reader
# who needs the wiki is exactly the reader who cannot infer `curate` from its name.
GROUPS = {
    "rails-flow": [
        ("Build", ["feature", "fix", "review"], "plan, implement and review a change"),
        ("Backlog", ["issues", "brief", "curate", "pr-comments", "report"],
         "turn a tracker or a review into work, and report toolchain bugs upstream"),
        ("Memory", ["brain", "brain-review", "brain-sync", "handoff"],
         "durable project memory that survives a session ending"),
        ("Autonomous", ["drive", "escalate", "toolchain-check"],
         "one action per tick, asking the human asynchronously when it must"),
        ("Setup", ["setup-flow", "explain", "graph"], "scaffold the flow into a project"),
    ],
    "design-flow": [
        ("Setup", ["setup", "tokens"], "design system, tokens and the brand pack"),
        ("Build", ["component", "variants", "mobile"], "build UI against the system"),
        ("Review", ["audit", "critique"], "conformance is the gate; taste is the lens"),
        ("Assets", ["assets", "generate"],
         "the curated asset library, and generation that mostly refuses"),
    ],
    "qa-flow": [
        ("Setup", ["setup-qa"], "scaffold the QA lane"),
        ("Plan", ["cases"], "derive cases from the brief, not from the diff"),
        ("Run", ["verify", "functional", "smoke", "crawl"], "produce evidence, not assurances"),
        ("Sign-off", ["certify"], "the only command that can say a change is ready"),
    ],
    "pipeline": [
        ("Setup", ["setup-pipeline", "install-hooks"], "wire the lifecycle into a project"),
        ("Run", ["pipeline", "status", "ack"], "build → verify → certify, with circuit breakers"),
        ("Release", ["release"], "cut it"),
        ("Cloud", ["setup-cloud", "deploy-cloud"], "deploy on demand"),
    ],
}


def read_manifest() -> dict:
    try:
        return json.loads(MANIFEST.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise SystemExit(f"cannot read {MANIFEST}: {exc}")


def plugin_commands(name: str) -> list[str]:
    d = ROOT / "plugins" / name / "commands"
    return sorted(p.stem for p in d.glob("*.md")) if d.is_dir() else []


# YAML block-scalar indicators. `description: >-` puts the text on the FOLLOWING indented lines, so
# reading the rest of the `description:` line returns the marker itself -- and the wiki published
# `>-` as the description for five of seven skills (#680). Two skills use single-line descriptions
# and rendered correctly, which is why it survived: it looks fine wherever you happen to check.
_BLOCK_SCALAR = ("|", "|-", "|+", ">", ">-", ">+")


def frontmatter_description(path: Path) -> str:
    """The `description:` from a markdown file's YAML frontmatter, block scalars included.

    #680. Returns "" only when there is genuinely nothing to read -- never a marker, never a
    fragment of syntax. The caller refuses to render an empty one rather than publishing a blank,
    because the failure this replaces was printing YAML where prose belonged.
    """
    if not path.is_file():
        return ""
    lines = path.read_text(encoding="utf-8").splitlines()
    for i, line in enumerate(lines):
        if not line.startswith("description:"):
            continue
        rest = line.split(":", 1)[1].strip()
        if rest and rest not in _BLOCK_SCALAR:
            return rest
        # A BLOCK SCALAR: the text is the indented run that follows, folded to one line. Stopping at
        # the first unindented line keeps the next frontmatter key out of the description -- reading
        # to the closing `---` would swallow `argument-hint:` and print it as prose.
        folded: list[str] = []
        for nxt in lines[i + 1:]:
            if not nxt.strip():
                break
            if not nxt.startswith((" ", "\t")):
                break
            folded.append(nxt.strip())
        return " ".join(folded)
    return ""


def first_sentence(text: str, limit: int = 200) -> str:
    """The lead clause of a description — enough to choose by, not the whole contract."""
    for stop in (". ", " — ", " -- "):
        if stop in text:
            return text.split(stop)[0].rstrip(".") + "."
    return text[:limit]


def skill_description(name: str) -> str:
    """The skill's own frontmatter description, trimmed to its first sentence."""
    return first_sentence(frontmatter_description(ROOT / "skills" / name / "SKILL.md"))


def command_line(plugin: str, name: str) -> str:
    """One command's line: its name AND what it does. #680.

    Every one of the 43 shipped commands carries a frontmatter `description:` -- required, present,
    and read by nothing. The page listed bare names, which is a table of contents rather than a
    reference: it said a command existed and not what it did, what it took, or what it produced.
    Same shape as `use_cases` before #639, in the script written to stop the docs rotting.

    A MISSING DESCRIPTION IS NAMED, not blanked. A silently description-less row reads as a command
    that does nothing worth saying, and the whole defect this replaces was publishing a placeholder
    where prose belonged.
    """
    desc = first_sentence(
        frontmatter_description(ROOT / "plugins" / plugin / "commands" / f"{name}.md"))
    if not desc:
        return f"- `/{plugin}:{name}` — _no `description:` in its frontmatter_\n"
    return f"- `/{plugin}:{name}` — {desc}\n"


def page_commands() -> str:
    out = [BANNER, "# Command reference\n",
           "Every command the marketplace ships, grouped by what you are trying to do.\n",
           "Commands are namespaced by plugin: `/rails-flow:feature`, `/qa-flow:verify`.\n"]
    total = 0
    for plugin, groups in GROUPS.items():
        available = set(plugin_commands(plugin))
        if not available:
            continue
        out.append(f"\n## `{plugin}`\n")
        listed: set[str] = set()
        for heading, names, why in groups:
            present = [n for n in names if n in available]
            if not present:
                continue
            listed.update(present)
            out.append(f"**{heading}** — {why}\n")
            out.append("".join(command_line(plugin, n) for n in sorted(present)))
            out.append("")
        # A command that exists and is in no group is LISTED, not dropped. Silently omitting it is
        # how the old README came to name 5 of 42 -- the reader cannot tell absence from oversight.
        ungrouped = sorted(available - listed)
        if ungrouped:
            out.append("**Ungrouped** — shipped but not yet placed in a group above\n")
            out.append("".join(command_line(plugin, n) for n in ungrouped))
            out.append("")
        total += len(available)
    out.append(f"\n---\n\n**{total} commands** across {len(GROUPS)} plugins.\n")
    return "\n".join(out)


def page_skills() -> str:
    manifest = read_manifest()
    bundled = next((p.get("skills", []) for p in manifest["plugins"]
                    if p["name"] == "rails-stack"), [])
    names = [Path(s).name for s in bundled]
    out = [BANNER, "# Skills reference\n",
           "Skills are **doctrine**, not commands: install them and Claude writes different code.\n",
           f"All {len(names)} ship in the `rails-stack` plugin, and each is also downloadable as a\n"
           "standalone `.skill` for claude.ai.\n\n"]
    for name in names:
        desc = skill_description(name)
        refs = sorted((ROOT / "skills" / name / "references").glob("*.md"))
        out.append(f"## `{name}`\n")
        if desc:
            out.append(f"{desc}\n")
        if refs:
            out.append(f"{len(refs)} reference file(s): "
                       + ", ".join(f"`{r.stem}`" for r in refs) + "\n")
        out.append("")
    return "\n".join(out)


def page_plugins() -> str:
    manifest = read_manifest()
    out = [BANNER, "# Plugin reference\n",
           f"Marketplace **{manifest['metadata']['version']}**.\n\n",
           "| plugin | version | commands | what it does |\n|---|---|---|---|\n"]
    for p in manifest["plugins"]:
        name = p["name"]
        ver = p.get("version") or _plugin_json_version(name) or "—"
        cmds = len(plugin_commands(name))
        desc = p["description"].split("—")[0].split(" - ")[0].strip()
        out.append(f"| `{name}` | {ver} | {cmds or '—'} | {desc[:88]} |\n")
    out.append("\n`rails-stack` ships **no commands** — it is doctrine only, which is why installing "
               "it changes what Claude writes without adding anything to type.\n")
    return "".join(out)


def _plugin_json_version(name: str) -> str:
    p = ROOT / "plugins" / name / ".claude-plugin" / "plugin.json"
    if not p.is_file():
        return ""
    try:
        return json.loads(p.read_text(encoding="utf-8")).get("version", "")
    except ValueError:
        return ""


BUILDERS = {"Command-Reference.md": page_commands,
            "Skills-Reference.md": page_skills,
            "Plugin-Reference.md": page_plugins}


def check_descriptions() -> list[str]:
    """No generated page may publish YAML syntax, or a command with nothing said about it. #680.

    The wiki printed `>-` as the description for five of seven skills, and listed 43 commands whose
    descriptions it already had. Both were invisible because two skills used single-line descriptions
    and rendered fine — it looked correct wherever you happened to check.

    So the check is on the RENDERED pages, not the parser: a parser test proves the function works
    and this proves the published bytes do. Those are different claims, and the one that shipped
    wrong was the second.
    """
    problems: list[str] = []
    for page in ("Skills-Reference.md", "Command-Reference.md", "Plugin-Reference.md"):
        path = WIKI / page
        if not path.is_file():
            continue
        for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if line.strip() in _BLOCK_SCALAR:
                problems.append(
                    f"docs/wiki/{page}:{n} publishes {line.strip()!r} — a YAML block-scalar marker "
                    f"rendered as prose. The description is on the indented lines that follow it.")
    cmds = WIKI / "Command-Reference.md"
    if cmds.is_file():
        bare = [ln.strip() for ln in cmds.read_text(encoding="utf-8").splitlines()
                if ln.startswith("- `/") and "—" not in ln]
        if bare:
            problems.append(
                f"{len(bare)} command(s) in Command-Reference carry no description, e.g. "
                f"{bare[0]!r}. Every shipped command has one in its frontmatter; a bare name is a "
                f"table of contents, not a reference.")
    return problems


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail on drift instead of writing")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args(argv)
    if args.selftest:
        return selftest()

    WIKI.mkdir(parents=True, exist_ok=True)
    drift = []
    for name, build in BUILDERS.items():
        want = build()
        path = WIKI / name
        if args.check:
            # The blob at HEAD, never the working copy (#833). A page rebuilt and never staged is
            # invisible to every other clone while sitting right there on disk; comparing the
            # working copy waved exactly that through locally and failed it in CI.
            committed = subprocess.run(
                ["git", "show", f"HEAD:{path.relative_to(ROOT).as_posix()}"],
                cwd=ROOT, capture_output=True, text=True, timeout=30)
            if committed.returncode != 0 or committed.stdout != want:
                drift.append(name)
        else:
            path.write_text(want, encoding="utf-8")
    if args.check:
        for d in drift:
            print(f"DRIFT: docs/wiki/{d} is not a clean build — a command, skill or version moved "
                  f"and the page was not rebuilt.")
        # #680. Drift is "the page does not match a rebuild"; this is "the page is WRONG even
        # though it matches" — a rebuild that faithfully republishes `>-` drifts from nothing.
        bad = check_descriptions()
        for b in bad:
            print(f"CONTENT: {b}")
        print("  -> python3 scripts/build_wiki.py && git add docs/wiki/" if drift or bad
              else "wiki reference pages are current.")
        return 1 if (drift or bad) else 0
    print(f"wrote {len(BUILDERS)} page(s) to docs/wiki/")
    return 0


def selftest() -> int:
    checks, failures = 0, []

    def check(label, cond):
        nonlocal checks
        checks += 1
        if not cond:
            failures.append(label)

    # -- #680: descriptions ------------------------------------------------
    import tempfile as _tf

    def _fm(body: str) -> str:
        with _tf.NamedTemporaryFile("w", suffix=".md", delete=False, encoding="utf-8") as fh:
            fh.write(body)
        return frontmatter_description(Path(fh.name))

    # A BLOCK SCALAR puts its text on the following indented lines. Reading the rest of the
    # `description:` line returns the marker, and the wiki published `>-` for five of seven skills.
    check("a `>-` block scalar folds its indented lines",
          _fm("---\nname: x\ndescription: >-\n  first line\n  second line\n---\n")
          == "first line second line")
    check("...and `|` too", _fm("---\ndescription: |\n  kept\n---\n") == "kept")
    check("a single-line description still works",
          _fm("---\ndescription: one line\n---\n") == "one line")
    # STOP AT THE NEXT KEY, or the description swallows `argument-hint:` and prints it as prose.
    check("...and folding stops before the next frontmatter key",
          _fm("---\ndescription: >-\n  the text\nargument-hint: <x>\n---\n") == "the text")
    check("a file with no description reads empty", _fm("---\nname: x\n---\n") == "")

    # THE CHECK IS ON THE RENDERED PAGES, not the parser. A parser test proves the function works;
    # this proves the published bytes do, and the one that shipped wrong was the second.
    check("the built pages publish no YAML marker and no bare command",
          check_descriptions() == [])

    global WIKI
    _real = WIKI
    try:
        WIKI = Path(_tf.mkdtemp())
        (WIKI / "Skills-Reference.md").write_text("## `x`\n\n>-\n", encoding="utf-8")
        (WIKI / "Command-Reference.md").write_text("- `/p:bare`\n", encoding="utf-8")
        found = check_descriptions()
        check("a published block-scalar marker is caught",
              any("block-scalar marker" in f for f in found))
        check("...and a command with no description is caught",
              any("no description" in f for f in found))
    finally:
        WIKI = _real

    cmds = page_commands()
    # EVERY command must appear. The old README named 5 of 42, and the reader could not tell an
    # omission from a command that does not exist.
    missing = [f"{pl}:{c}" for pl in GROUPS for c in plugin_commands(pl)
               if f"/{pl}:{c}`" not in cmds]
    check(f"every command appears (missing: {missing[:3]})", not missing)
    check("...and the total is stated", "commands** across" in cmds)
    # A command in no group is LISTED, never dropped -- silent omission is the defect being fixed.
    # Tested by actually removing one from its group and rebuilding, because the first version of
    # this assertion was `"Ungrouped" in page_commands.__doc__ or True` -- a gate that cannot fail,
    # written into the selftest of a script whose whole job is refusing to go stale silently.
    # sys.modules[__name__], not `import build_wiki`: run as a script this module IS `__main__`,
    # so importing by name creates a SECOND module object and the rebind lands on the wrong one --
    # the test then passes or fails for a reason unrelated to what it claims to check.
    _self = sys.modules[__name__]
    original = _self.GROUPS
    try:
        victim = plugin_commands("rails-flow")[0]
        _self.GROUPS = {"rails-flow": [(h, [n for n in names if n != victim], why)
                                       for h, names, why in original["rails-flow"]]}
        rebuilt = page_commands()
        check(f"an ungrouped command ({victim}) is listed, not dropped",
              "Ungrouped" in rebuilt and f"/rails-flow:{victim}`" in rebuilt)
    finally:
        _self.GROUPS = original

    skills = page_skills()
    declared = [Path(s).name for s in next(
        (p.get("skills", []) for p in read_manifest()["plugins"] if p["name"] == "rails-stack"), [])]
    check(f"every bundled skill appears ({len(declared)})",
          all(f"## `{s}`" in skills for s in declared))
    check("the count is derived, not typed", f"All {len(declared)} ship" in skills)

    plugins = page_plugins()
    check("every plugin appears",
          all(f"`{p['name']}`" in plugins for p in read_manifest()["plugins"]))
    check("the marketplace version is the real one",
          read_manifest()["metadata"]["version"] in plugins)
    # rails-stack has no commands; printing 0 would read as a defect rather than a design choice.
    check("a plugin with no commands shows an em dash, not 0", "| — |" in plugins)

    # LINK FORM. A GitHub wiki resolves a sibling page by NAME, without the extension: `](Page.md)`
    # points at a RAW FILE, not the rendered page. That shipped, and every cross-page link in the
    # wiki was broken until a reader clicked one. And `../x.md` cannot resolve at all, because the
    # wiki is a different repository -- those must be absolute blob URLs.
    wiki_dir = ROOT / "docs" / "wiki"
    if wiki_dir.is_dir():
        for page in sorted(wiki_dir.glob("*.md")):
            body = page.read_text(encoding="utf-8")
            check(f"{page.name}: no `.md` in sibling links",
                  not re.search(r"\]\([A-Za-z][A-Za-z0-9-]*\.md\)", body))
            check(f"{page.name}: no relative cross-repo links",
                  "](../" not in body)
        for required in ("_Footer.md", "_Sidebar.md", "Home.md"):
            check(f"{required} exists", (wiki_dir / required).is_file())

    for name in GENERATED:
        check(f"{name} has a generated banner", BANNER.strip()[:20] in BUILDERS[name]())

    for f in failures:
        print(f"FAIL {f}")
    print(f"ran {checks} build-wiki assertion(s)")
    print("no findings." if not failures else f"{len(failures)} finding(s).")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
